### ISSUE TITLE
Cell type annotation

### ISSUE THREAD

**Issue by Pikachu233** [kasperlab/Joost_et_al_2020_Cell_Stem_Cell#1]
Hello!

Congratulation on this wonderful paper! Also, thanks a lot for sharing your data, which, I believe, is an important resource to study hair growth and quiescence. As I tried to look into the dataset from GEO, I realized there isn't a supplemented document about your detailed 1st and 2nd level cell-type annotation for each cell. Although I found codes here, as a non-python user, it's a little hard for me to get the results. If it's possible, I wonder if you could share the cell type annotation? Really appreciate your help!

**Comment by kasperlab** [comment]
Uploaded the following files:

**cell_types_cluster_names.txt:** Dictionary linking cluster names to cell type annotations used in CSC paper
**celltypes_1st_level.txt:** 1st level clusters, main data
**celltypes_2nd_level.txt:** 2nd level clusters, main data
**celltypes_validation_1st_level_logit.txt:** logit classification results linking 1st level clusters to validation dataset
**celltypes_validation_2nd_level_logit.txt:** logit classification results linking 2nd level clusters to validation dataset

**Comment by Pikachu233** [comment]
Thanks very much, @kasperlab!
