### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by s849** [kasperlab/Joost_et_al_2020_Cell_Stem_Cell#2]
Hello,

Congratulations on your beautiful paper. I am trying to go through your data using the code you provided, but I ran into an issue early on. In Joost_et_al0a_analysis.ipynb line 33, what is the "sf" file coming from? I am not sure if this is supposed to get generated prior line 33 - the code I ran did not generate it. Is this something that you can provide, or a missing line of code that would generate this?

Thank you!

**Comment by kasperlab** [comment]
Hi,

This notebook was generated before we had good integration of Python and R code in single jupyer notebooks. The sf file contains size factors which were generated with the scran R package using the computeSumFactors() function with default parameters. Specifically, I ran the following commands:

#import libraries

library(SingleCellExperiment)
library(scran)

#import and wrangle data

all.counts <- read.table(file = "{PATH}/201806201840_seq_val.txt", 
header = TRUE, as.is = TRUE, row.names = 1)
all.counts <- as.matrix(all.counts)

#get size factors

sce <- SingleCellExperiment(list(counts=all.counts))
sce <- computeSumFactors(sce)
sf = sizeFactors(sce)
sf = as.data.frame(sf)
rownames(sf) = colnames(all.counts)
write.table(sf, file = "{PATH}/201806201840_sf_val.txt", sep = "\t", row.names=TRUE, col.names=TRUE)

Best
Simon
